import '../../assets/img/icon/icon-arrow-back.svg'
import '../../assets/img/icon/icon-arrow-forward.svg'
import '../../assets/img/icon/icon-arrow-down.svg'
import '../../assets/img/icon/icon-arrow-left.svg'
import '../../assets/img/icon/icon-arrow-right.svg'